# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

angular.module("myapp", []).controller "CalculatorController", ["$scope", ($scope) ->
  $scope.money = {}
  $scope.money.inputAmount = 200
  $scope.changeInput = () ->
    $scope.money.outputAmount = $scope.money.inputAmount * 2
    $scope.money.savedAmount = $scope.money.inputAmount * 0.0253
  $scope.changeOutput = () ->
    $scope.money.inputAmount = $scope.money.outputAmount / 2
    $scope.money.savedAmount = $scope.money.inputAmount * 0.0253
  $scope.changeInput();
]

$(document).on 'ready', ->
  $('.js-find-out').on 'click', ->
    $('html, body').animate scrollTop: '700px'
    return
  return


# ---
# generated by js2coffee 2.0.3